runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\..*)
  static_files: build/\1
  upload: build/(.*\..*)
  expiration: 10m
- url: /(.+)/
  static_files: build/\1/index.html
  upload: build/(.+)/index.html
  expiration: 0
- url: /(.+)
  static_files: build/\1/index.html
  upload: build/(.+)/index.html
  expiration: 0
- url: /
  static_files: build/index.html
  upload: build/index.html
  expiration: 0
 
skip_files:
- (?!build).*
